services:
  db:
    image: postgres:16
    container_name: kanban_db
    environment:
      POSTGRES_DB: kanbandb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - kanban-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanban_api
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kanbandb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kanban-network

volumes:
  db_data:

networks:
  kanban-network:
